 module.exports = [{
ranking: 1,
rating: 3177,
name: "Pikabooiseeu",
realmId: 11,
realmName: "Tichondrius",
realmSlug: "tichondrius",
raceId: 1,
classId: 4,
specId: 261,
factionId: 0,
genderId: 1,
seasonWins: 485,
seasonLosses: 165,
weeklyWins: 14,
weeklyLosses: 2
},
{
ranking: 2,
rating: 3106,
name: "Jahmilli",
realmId: 11,
realmName: "Tichondrius",
realmSlug: "tichondrius",
raceId: 1,
classId: 8,
specId: 64,
factionId: 0,
genderId: 1,
seasonWins: 1197,
seasonLosses: 549,
weeklyWins: 14,
weeklyLosses: 2
},
{
ranking: 3,
rating: 3093,
name: "Kíritó",
realmId: 11,
realmName: "Tichondrius",
realmSlug: "tichondrius",
raceId: 1,
classId: 8,
specId: 64,
factionId: 0,
genderId: 1,
seasonWins: 952,
seasonLosses: 336,
weeklyWins: 0,
weeklyLosses: 0
},
{
ranking: 4,
rating: 3090,
name: "Goreckis",
realmId: 1145,
realmName: "Mug'thol",
realmSlug: "mugthol",
raceId: 4,
classId: 11,
specId: 105,
factionId: 0,
genderId: 1,
seasonWins: 860,
seasonLosses: 351,
weeklyWins: 8,
weeklyLosses: 2
},
{
ranking: 5,
rating: 3082,
name: "Koobzy",
realmId: 16,
realmName: "Kel'Thuzad",
realmSlug: "kelthuzad",
raceId: 3,
classId: 2,
specId: 65,
factionId: 0,
genderId: 0,
seasonWins: 427,
seasonLosses: 176,
weeklyWins: 0,
weeklyLosses: 0
}]
